# Generated by Django 5.1.4 on 2025-01-01 15:45

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('second_name', models.CharField(max_length=120)),
                ('height', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('matches_won', models.PositiveSmallIntegerField()),
                ('matches_lost', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
