# Generated by Django 5.1.4 on 2025-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxxing_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='weight_category',
            field=models.CharField(blank=True, default='Lightweight', editable=False, max_length=120),
        ),
    ]
