# Generated by Django 5.1.4 on 2025-02-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoxerPerformance",
        ),
    ]
