# Generated by Django 5.1.4 on 2025-01-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0002_boxer_weight_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rounds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_1", models.PositiveSmallIntegerField(default=0)),
                ("round_2", models.PositiveSmallIntegerField(default=0)),
                ("round_3", models.PositiveSmallIntegerField(default=0)),
                ("round_4", models.PositiveSmallIntegerField(default=0)),
                ("round_5", models.PositiveSmallIntegerField(default=0)),
                ("round_6", models.PositiveSmallIntegerField(default=0)),
                ("round_7", models.PositiveSmallIntegerField(default=0)),
                ("round_8", models.PositiveSmallIntegerField(default=0)),
                ("round_9", models.PositiveSmallIntegerField(default=0)),
                ("round_10", models.PositiveSmallIntegerField(default=0)),
                ("round_11", models.PositiveSmallIntegerField(default=0)),
                ("round_12", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="boxer",
            name="matches_lost",
        ),
        migrations.RemoveField(
            model_name="boxer",
            name="matches_won",
        ),
        migrations.AddField(
            model_name="boxer",
            name="fights_lost",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boxer",
            name="fights_played",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boxer",
            name="fights_tied",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boxer",
            name="fights_won",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="boxer",
            name="weight",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="BoxerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boxer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boxxing_api.boxer",
                    ),
                ),
                (
                    "total_rounds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boxxing_api.rounds",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boxer_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxer_1",
                        to="boxxing_api.boxermatch",
                    ),
                ),
                (
                    "boxer_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxer_2",
                        to="boxxing_api.boxermatch",
                    ),
                ),
            ],
        ),
    ]
