# Generated by Django 5.1.4 on 2025-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0002_delete_boxerperformance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="knockdowns",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="rounds_won",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="total_defense",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="matchresult",
            name="total_punces",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
