# Generated by Django 5.1.4 on 2025-02-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0003_alter_matchresult_knockdowns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchresult",
            name="punch_accuracy",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
