# Generated by Django 5.1.4 on 2025-01-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0003_rounds_remove_boxer_matches_lost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxermatch",
            name="boxer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contestant",
                to="boxxing_api.boxer",
            ),
        ),
        migrations.AlterField(
            model_name="boxermatch",
            name="total_rounds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="boxxing_api.rounds",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="boxer_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_contestant",
                to="boxxing_api.boxermatch",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="boxer_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_contestant",
                to="boxxing_api.boxermatch",
            ),
        ),
    ]
