# Generated by Django 5.1.4 on 2025-01-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boxxing_api",
            "0004_alter_boxermatch_boxer_alter_boxermatch_total_rounds_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxermatch",
            name="total_rounds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="total_rounds",
                to="boxxing_api.rounds",
            ),
        ),
    ]
