# Generated by Django 5.1.4 on 2025-02-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0004_alter_matchresult_punch_accuracy"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="win_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KO", "Knockout"),
                    ("TKO", "Technical Knockout"),
                    ("UD", "Unanonimous Decision"),
                    ("SD", "Split Decision"),
                    ("MD", "Majority Decision"),
                    ("Draw", "Draw"),
                    ("NC", "No Contest"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wins",
                to="boxxing_api.boxer",
            ),
        ),
    ]
