# Generated by Django 5.1.4 on 2025-02-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0005_match_win_method_match_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxer",
            name="fights_played",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="boxer_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_boxer_1",
                to="boxxing_api.boxer",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="boxer_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_boxer_2",
                to="boxxing_api.boxer",
                unique=True,
            ),
        ),
    ]
