# Generated by Django 5.1.4 on 2025-02-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0006_alter_boxer_fights_played_alter_match_boxer_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boxxing_api.boxer",
            ),
        ),
    ]
