# Generated by Django 5.1.4 on 2025-02-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxxing_api", "0007_alter_match_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wins",
                to="boxxing_api.boxer",
            ),
        ),
    ]
